name: Bug report
description: Report a problem or regression
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node version.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant console or network logs.
      render: shell
